[keyboard]
# Define keyboard bindings here
# Example placeholder (actual bindings need to be defined based on user preference)
bindings = [
    # { key = "Key", mods = "Modifiers", action = "Action" },
    # { key = "Key", mods = "Modifiers", chars = "Characters to send" },
    { key = "Right", mods = "Option", chars = "\u001BF" },
    { key = "Left", mods = "Option", chars = "\u001BB" },
]
